version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mahasiswa_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mahasiswa_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_soal1:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: mahasiswa_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: mahasiswa_db
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: mahasiswa_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata_soal1: